In [4]:
my_list=[1,2,3]

In [5]:
import numpy as np

In [7]:
arr =np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
mat = np.array(my_mat)

In [12]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [33]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.rand(5)

array([0.63952319, 0.08445109, 0.50570544, 0.70053095, 0.69413255])

In [36]:
np.random.rand(5,5)

array([[0.98996273, 0.74696919, 0.33867765, 0.23775911, 0.99005758],
       [0.04788682, 0.20473071, 0.17088096, 0.2353806 , 0.5130236 ],
       [0.15486685, 0.64228724, 0.86763504, 0.9206116 , 0.62895478],
       [0.2137861 , 0.43779228, 0.81835574, 0.70000184, 0.66983858],
       [0.90054578, 0.58397957, 0.24763358, 0.2539543 , 0.72769839]])

In [37]:
##random number from standard distributation
np.random.randn(2)

array([-1.15832007,  0.86930739])

In [38]:
np.random.randn(2,2)

array([[-1.78477545, -0.46310065],
       [-0.53883103,  0.61138312]])

In [41]:
np.random.randint(1,13,3)

array([2, 7, 9])

In [42]:
arr1 = np.arange(25)

In [43]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr = np.random.randint(0,50,10)

In [45]:
ranarr

array([37, 26, 30,  5, 47, 34, 14,  0, 22, 42])

In [46]:
##resgape method
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.max()

47

In [48]:
ranarr.min()

0

In [49]:
ranarr.argmax()

4

In [50]:
ranarr.argmin()

7

In [52]:
arr1 = arr1.reshape(5,5)
arr1.shape


(5, 5)

In [ ]:
arr.dtype